#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cosen
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eissy")]
	public partial class DataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Inserttjdp(tjdp instance);
    partial void Updatetjdp(tjdp instance);
    partial void Deletetjdp(tjdp instance);
    partial void InsertExceptionLog(ExceptionLog instance);
    partial void UpdateExceptionLog(ExceptionLog instance);
    partial void DeleteExceptionLog(ExceptionLog instance);
    partial void Insertdapei(dapei instance);
    partial void Updatedapei(dapei instance);
    partial void Deletedapei(dapei instance);
    partial void Insertareapic(areapic instance);
    partial void Updateareapic(areapic instance);
    partial void Deleteareapic(areapic instance);
    partial void Insertpromotions(promotions instance);
    partial void Updatepromotions(promotions instance);
    partial void Deletepromotions(promotions instance);
    partial void InsertStyle_EditionHandle(Style_EditionHandle instance);
    partial void UpdateStyle_EditionHandle(Style_EditionHandle instance);
    partial void DeleteStyle_EditionHandle(Style_EditionHandle instance);
    partial void InsertPeiHuo(PeiHuo instance);
    partial void UpdatePeiHuo(PeiHuo instance);
    partial void DeletePeiHuo(PeiHuo instance);
    partial void Insertuser_info(user_info instance);
    partial void Updateuser_info(user_info instance);
    partial void Deleteuser_info(user_info instance);
    partial void Insertrole_info(role_info instance);
    partial void Updaterole_info(role_info instance);
    partial void Deleterole_info(role_info instance);
    #endregion
		
		public DataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dianpu> dianpu
		{
			get
			{
				return this.GetTable<dianpu>();
			}
		}
		
		public System.Data.Linq.Table<style> style
		{
			get
			{
				return this.GetTable<style>();
			}
		}
		
		public System.Data.Linq.Table<tjdp> tjdp
		{
			get
			{
				return this.GetTable<tjdp>();
			}
		}
		
		public System.Data.Linq.Table<ExceptionLog> ExceptionLog
		{
			get
			{
				return this.GetTable<ExceptionLog>();
			}
		}
		
		public System.Data.Linq.Table<Up4Image> Up4Image
		{
			get
			{
				return this.GetTable<Up4Image>();
			}
		}
		
		public System.Data.Linq.Table<dapei> dapei
		{
			get
			{
				return this.GetTable<dapei>();
			}
		}
		
		public System.Data.Linq.Table<areapic> areapic
		{
			get
			{
				return this.GetTable<areapic>();
			}
		}
		
		public System.Data.Linq.Table<promotions> promotions
		{
			get
			{
				return this.GetTable<promotions>();
			}
		}
		
		public System.Data.Linq.Table<Style_EditionHandle> Style_EditionHandle
		{
			get
			{
				return this.GetTable<Style_EditionHandle>();
			}
		}
		
		public System.Data.Linq.Table<PeiHuo> PeiHuo
		{
			get
			{
				return this.GetTable<PeiHuo>();
			}
		}
		
		public System.Data.Linq.Table<user_info> user_info
		{
			get
			{
				return this.GetTable<user_info>();
			}
		}
		
		public System.Data.Linq.Table<role_info> role_info
		{
			get
			{
				return this.GetTable<role_info>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getdp")]
		public ISingleResult<getdpResult> getdp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string dt1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string dt2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> of)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid, dt1, dt2, of);
			return ((ISingleResult<getdpResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.report", IsComposable=true)]
		public object report([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sltType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string dt1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string dt2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string cond)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sltType, dt1, dt2, cond).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getchdbdetail", IsComposable=true)]
		public object getchdbdetail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string enddate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] string cond)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startdate, enddate, cond).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.zhizhaodan_proc")]
		public ISingleResult<zhizhaodan_procResult> zhizhaodan_proc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string dh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dh);
			return ((ISingleResult<zhizhaodan_procResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPeiHuo_Proc")]
		public ISingleResult<GetPeiHuo_ProcResult> GetPeiHuo_Proc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string style, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string zhid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), style, zhid);
			return ((ISingleResult<GetPeiHuo_ProcResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMan_No_Proc")]
		public ISingleResult<GetMan_No_ProcResult> GetMan_No_Proc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetMan_No_ProcResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Out_Excel_Proc")]
		public ISingleResult<Out_Excel_ProcResult> Out_Excel_Proc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string zdid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), zdid);
			return ((ISingleResult<Out_Excel_ProcResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_user_role")]
		public ISingleResult<get_user_roleResult> get_user_role([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string user_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_name);
			return ((ISingleResult<get_user_roleResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dianpu")]
	public partial class dianpu
	{
		
		private string _Use_id;
		
		private string _Use_nm;
		
		public dianpu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_id", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Use_id
		{
			get
			{
				return this._Use_id;
			}
			set
			{
				if ((this._Use_id != value))
				{
					this._Use_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Use_nm", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Use_nm
		{
			get
			{
				return this._Use_nm;
			}
			set
			{
				if ((this._Use_nm != value))
				{
					this._Use_nm = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.style")]
	public partial class style
	{
		
		private string _sty_no;
		
		private string _col_no;
		
		private string _Com_nm;
		
		private decimal _Unt_pr;
		
		public style()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sty_no", DbType="VarChar(8000)")]
		public string sty_no
		{
			get
			{
				return this._sty_no;
			}
			set
			{
				if ((this._sty_no != value))
				{
					this._sty_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_col_no", DbType="VarChar(8000)")]
		public string col_no
		{
			get
			{
				return this._col_no;
			}
			set
			{
				if ((this._col_no != value))
				{
					this._col_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_nm", DbType="VarChar(100)")]
		public string Com_nm
		{
			get
			{
				return this._Com_nm;
			}
			set
			{
				if ((this._Com_nm != value))
				{
					this._Com_nm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unt_pr", DbType="Decimal(18,8) NOT NULL")]
		public decimal Unt_pr
		{
			get
			{
				return this._Unt_pr;
			}
			set
			{
				if ((this._Unt_pr != value))
				{
					this._Unt_pr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tjdp")]
	public partial class tjdp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _use_id;
		
		private string _cbpicture;
		
		private string _tjdate;
		
		private string _remark;
		
		private string _mqu;
		
		private string _lqu1;
		
		private string _lqu2;
		
		private string _bqu1;
		
		private string _bqu2;
		
		private string _aqu1;
		
		private string _aqu2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onuse_idChanging(string value);
    partial void Onuse_idChanged();
    partial void OncbpictureChanging(string value);
    partial void OncbpictureChanged();
    partial void OntjdateChanging(string value);
    partial void OntjdateChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnmquChanging(string value);
    partial void OnmquChanged();
    partial void Onlqu1Changing(string value);
    partial void Onlqu1Changed();
    partial void Onlqu2Changing(string value);
    partial void Onlqu2Changed();
    partial void Onbqu1Changing(string value);
    partial void Onbqu1Changed();
    partial void Onbqu2Changing(string value);
    partial void Onbqu2Changed();
    partial void Onaqu1Changing(string value);
    partial void Onaqu1Changed();
    partial void Onaqu2Changing(string value);
    partial void Onaqu2Changed();
    #endregion
		
		public tjdp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_id", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string use_id
		{
			get
			{
				return this._use_id;
			}
			set
			{
				if ((this._use_id != value))
				{
					this.Onuse_idChanging(value);
					this.SendPropertyChanging();
					this._use_id = value;
					this.SendPropertyChanged("use_id");
					this.Onuse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbpicture", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string cbpicture
		{
			get
			{
				return this._cbpicture;
			}
			set
			{
				if ((this._cbpicture != value))
				{
					this.OncbpictureChanging(value);
					this.SendPropertyChanging();
					this._cbpicture = value;
					this.SendPropertyChanged("cbpicture");
					this.OncbpictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tjdate", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tjdate
		{
			get
			{
				return this._tjdate;
			}
			set
			{
				if ((this._tjdate != value))
				{
					this.OntjdateChanging(value);
					this.SendPropertyChanging();
					this._tjdate = value;
					this.SendPropertyChanged("tjdate");
					this.OntjdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(100)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mqu", DbType="VarChar(10)")]
		public string mqu
		{
			get
			{
				return this._mqu;
			}
			set
			{
				if ((this._mqu != value))
				{
					this.OnmquChanging(value);
					this.SendPropertyChanging();
					this._mqu = value;
					this.SendPropertyChanged("mqu");
					this.OnmquChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lqu1", DbType="VarChar(10)")]
		public string lqu1
		{
			get
			{
				return this._lqu1;
			}
			set
			{
				if ((this._lqu1 != value))
				{
					this.Onlqu1Changing(value);
					this.SendPropertyChanging();
					this._lqu1 = value;
					this.SendPropertyChanged("lqu1");
					this.Onlqu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lqu2", DbType="VarChar(10)")]
		public string lqu2
		{
			get
			{
				return this._lqu2;
			}
			set
			{
				if ((this._lqu2 != value))
				{
					this.Onlqu2Changing(value);
					this.SendPropertyChanging();
					this._lqu2 = value;
					this.SendPropertyChanged("lqu2");
					this.Onlqu2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqu1", DbType="VarChar(10)")]
		public string bqu1
		{
			get
			{
				return this._bqu1;
			}
			set
			{
				if ((this._bqu1 != value))
				{
					this.Onbqu1Changing(value);
					this.SendPropertyChanging();
					this._bqu1 = value;
					this.SendPropertyChanged("bqu1");
					this.Onbqu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqu2", DbType="VarChar(10)")]
		public string bqu2
		{
			get
			{
				return this._bqu2;
			}
			set
			{
				if ((this._bqu2 != value))
				{
					this.Onbqu2Changing(value);
					this.SendPropertyChanging();
					this._bqu2 = value;
					this.SendPropertyChanged("bqu2");
					this.Onbqu2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aqu1", DbType="VarChar(10)")]
		public string aqu1
		{
			get
			{
				return this._aqu1;
			}
			set
			{
				if ((this._aqu1 != value))
				{
					this.Onaqu1Changing(value);
					this.SendPropertyChanging();
					this._aqu1 = value;
					this.SendPropertyChanged("aqu1");
					this.Onaqu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aqu2", DbType="VarChar(10)")]
		public string aqu2
		{
			get
			{
				return this._aqu2;
			}
			set
			{
				if ((this._aqu2 != value))
				{
					this.Onaqu2Changing(value);
					this.SendPropertyChanging();
					this._aqu2 = value;
					this.SendPropertyChanged("aqu2");
					this.Onaqu2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExceptionLog")]
	public partial class ExceptionLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ErrorDate;
		
		private string _ExceptionType;
		
		private string _Message;
		
		private string _StackTrace;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnErrorDateChanging(string value);
    partial void OnErrorDateChanged();
    partial void OnExceptionTypeChanging(string value);
    partial void OnExceptionTypeChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnStackTraceChanging(string value);
    partial void OnStackTraceChanged();
    #endregion
		
		public ExceptionLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorDate", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ErrorDate
		{
			get
			{
				return this._ErrorDate;
			}
			set
			{
				if ((this._ErrorDate != value))
				{
					this.OnErrorDateChanging(value);
					this.SendPropertyChanging();
					this._ErrorDate = value;
					this.SendPropertyChanged("ErrorDate");
					this.OnErrorDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionType", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ExceptionType
		{
			get
			{
				return this._ExceptionType;
			}
			set
			{
				if ((this._ExceptionType != value))
				{
					this.OnExceptionTypeChanging(value);
					this.SendPropertyChanging();
					this._ExceptionType = value;
					this.SendPropertyChanged("ExceptionType");
					this.OnExceptionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StackTrace", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string StackTrace
		{
			get
			{
				return this._StackTrace;
			}
			set
			{
				if ((this._StackTrace != value))
				{
					this.OnStackTraceChanging(value);
					this.SendPropertyChanging();
					this._StackTrace = value;
					this.SendPropertyChanged("StackTrace");
					this.OnStackTraceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Up4Image")]
	public partial class Up4Image
	{
		
		private string _Code;
		
		private System.Data.Linq.Binary _StyleImage;
		
		public Up4Image()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(100)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StyleImage
		{
			get
			{
				return this._StyleImage;
			}
			set
			{
				if ((this._StyleImage != value))
				{
					this._StyleImage = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dapei")]
	public partial class dapei : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masterstyle;
		
		private string _type;
		
		private string _legging1;
		
		private string _legging2;
		
		private string _bottom1;
		
		private string _bottom2;
		
		private string _accessory1;
		
		private string _accessory2;
		
		private string _cbpicture;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasterstyleChanging(string value);
    partial void OnmasterstyleChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onlegging1Changing(string value);
    partial void Onlegging1Changed();
    partial void Onlegging2Changing(string value);
    partial void Onlegging2Changed();
    partial void Onbottom1Changing(string value);
    partial void Onbottom1Changed();
    partial void Onbottom2Changing(string value);
    partial void Onbottom2Changed();
    partial void Onaccessory1Changing(string value);
    partial void Onaccessory1Changed();
    partial void Onaccessory2Changing(string value);
    partial void Onaccessory2Changed();
    partial void OncbpictureChanging(string value);
    partial void OncbpictureChanged();
    #endregion
		
		public dapei()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterstyle", DbType="VarChar(50)")]
		public string masterstyle
		{
			get
			{
				return this._masterstyle;
			}
			set
			{
				if ((this._masterstyle != value))
				{
					this.OnmasterstyleChanging(value);
					this.SendPropertyChanging();
					this._masterstyle = value;
					this.SendPropertyChanged("masterstyle");
					this.OnmasterstyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_legging1", DbType="VarChar(50)")]
		public string legging1
		{
			get
			{
				return this._legging1;
			}
			set
			{
				if ((this._legging1 != value))
				{
					this.Onlegging1Changing(value);
					this.SendPropertyChanging();
					this._legging1 = value;
					this.SendPropertyChanged("legging1");
					this.Onlegging1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_legging2", DbType="VarChar(50)")]
		public string legging2
		{
			get
			{
				return this._legging2;
			}
			set
			{
				if ((this._legging2 != value))
				{
					this.Onlegging2Changing(value);
					this.SendPropertyChanging();
					this._legging2 = value;
					this.SendPropertyChanged("legging2");
					this.Onlegging2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottom1", DbType="VarChar(50)")]
		public string bottom1
		{
			get
			{
				return this._bottom1;
			}
			set
			{
				if ((this._bottom1 != value))
				{
					this.Onbottom1Changing(value);
					this.SendPropertyChanging();
					this._bottom1 = value;
					this.SendPropertyChanged("bottom1");
					this.Onbottom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottom2", DbType="VarChar(50)")]
		public string bottom2
		{
			get
			{
				return this._bottom2;
			}
			set
			{
				if ((this._bottom2 != value))
				{
					this.Onbottom2Changing(value);
					this.SendPropertyChanging();
					this._bottom2 = value;
					this.SendPropertyChanged("bottom2");
					this.Onbottom2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory1", DbType="VarChar(50)")]
		public string accessory1
		{
			get
			{
				return this._accessory1;
			}
			set
			{
				if ((this._accessory1 != value))
				{
					this.Onaccessory1Changing(value);
					this.SendPropertyChanging();
					this._accessory1 = value;
					this.SendPropertyChanged("accessory1");
					this.Onaccessory1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory2", DbType="VarChar(50)")]
		public string accessory2
		{
			get
			{
				return this._accessory2;
			}
			set
			{
				if ((this._accessory2 != value))
				{
					this.Onaccessory2Changing(value);
					this.SendPropertyChanging();
					this._accessory2 = value;
					this.SendPropertyChanged("accessory2");
					this.Onaccessory2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbpicture", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cbpicture
		{
			get
			{
				return this._cbpicture;
			}
			set
			{
				if ((this._cbpicture != value))
				{
					this.OncbpictureChanging(value);
					this.SendPropertyChanging();
					this._cbpicture = value;
					this.SendPropertyChanged("cbpicture");
					this.OncbpictureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.areapic")]
	public partial class areapic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _dpid;
		
		private string _pic_name;
		
		private string _remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndpidChanging(string value);
    partial void OndpidChanged();
    partial void Onpic_nameChanging(string value);
    partial void Onpic_nameChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    #endregion
		
		public areapic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpid", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string dpid
		{
			get
			{
				return this._dpid;
			}
			set
			{
				if ((this._dpid != value))
				{
					this.OndpidChanging(value);
					this.SendPropertyChanging();
					this._dpid = value;
					this.SendPropertyChanged("dpid");
					this.OndpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pic_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pic_name
		{
			get
			{
				return this._pic_name;
			}
			set
			{
				if ((this._pic_name != value))
				{
					this.Onpic_nameChanging(value);
					this.SendPropertyChanging();
					this._pic_name = value;
					this.SendPropertyChanged("pic_name");
					this.Onpic_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(1000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.promotions")]
	public partial class promotions : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _p_id;
		
		private string _p_content;
		
		private string _remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_idChanging(int value);
    partial void Onp_idChanged();
    partial void Onp_contentChanging(string value);
    partial void Onp_contentChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    #endregion
		
		public promotions()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int p_id
		{
			get
			{
				return this._p_id;
			}
			set
			{
				if ((this._p_id != value))
				{
					this.Onp_idChanging(value);
					this.SendPropertyChanging();
					this._p_id = value;
					this.SendPropertyChanged("p_id");
					this.Onp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_content", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string p_content
		{
			get
			{
				return this._p_content;
			}
			set
			{
				if ((this._p_content != value))
				{
					this.Onp_contentChanging(value);
					this.SendPropertyChanging();
					this._p_content = value;
					this.SendPropertyChanged("p_content");
					this.Onp_contentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(1000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Style_EditionHandle")]
	public partial class Style_EditionHandle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StyleCode;
		
		private string _EditionHandle;
		
		private System.Nullable<int> _p_id;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStyleCodeChanging(string value);
    partial void OnStyleCodeChanged();
    partial void OnEditionHandleChanging(string value);
    partial void OnEditionHandleChanged();
    partial void Onp_idChanging(System.Nullable<int> value);
    partial void Onp_idChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public Style_EditionHandle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleCode", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StyleCode
		{
			get
			{
				return this._StyleCode;
			}
			set
			{
				if ((this._StyleCode != value))
				{
					this.OnStyleCodeChanging(value);
					this.SendPropertyChanging();
					this._StyleCode = value;
					this.SendPropertyChanged("StyleCode");
					this.OnStyleCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditionHandle", DbType="VarChar(50)")]
		public string EditionHandle
		{
			get
			{
				return this._EditionHandle;
			}
			set
			{
				if ((this._EditionHandle != value))
				{
					this.OnEditionHandleChanging(value);
					this.SendPropertyChanging();
					this._EditionHandle = value;
					this.SendPropertyChanged("EditionHandle");
					this.OnEditionHandleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_id", DbType="Int")]
		public System.Nullable<int> p_id
		{
			get
			{
				return this._p_id;
			}
			set
			{
				if ((this._p_id != value))
				{
					this.Onp_idChanging(value);
					this.SendPropertyChanging();
					this._p_id = value;
					this.SendPropertyChanged("p_id");
					this.Onp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(1000)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PeiHuo")]
	public partial class PeiHuo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _zhid;
		
		private string _use_id;
		
		private string _style;
		
		private System.Nullable<int> _s105;
		
		private System.Nullable<int> _m120;
		
		private System.Nullable<int> _l130;
		
		private System.Nullable<int> _xl140;
		
		private System.Nullable<int> _xxl155;
		
		private System.Nullable<int> _total_num;
		
		private System.Nullable<decimal> _unt_pr;
		
		private System.Nullable<decimal> _total_money;
		
		private string _ph_date;
		
		private string _ph_update_date;
		
		private string _ph_per;
		
		private string _ph_update_per;
		
		private string _remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnzhidChanging(string value);
    partial void OnzhidChanged();
    partial void Onuse_idChanging(string value);
    partial void Onuse_idChanged();
    partial void OnstyleChanging(string value);
    partial void OnstyleChanged();
    partial void Ons105Changing(System.Nullable<int> value);
    partial void Ons105Changed();
    partial void Onm120Changing(System.Nullable<int> value);
    partial void Onm120Changed();
    partial void Onl130Changing(System.Nullable<int> value);
    partial void Onl130Changed();
    partial void Onxl140Changing(System.Nullable<int> value);
    partial void Onxl140Changed();
    partial void Onxxl155Changing(System.Nullable<int> value);
    partial void Onxxl155Changed();
    partial void Ontotal_numChanging(System.Nullable<int> value);
    partial void Ontotal_numChanged();
    partial void Onunt_prChanging(System.Nullable<decimal> value);
    partial void Onunt_prChanged();
    partial void Ontotal_moneyChanging(System.Nullable<decimal> value);
    partial void Ontotal_moneyChanged();
    partial void Onph_dateChanging(string value);
    partial void Onph_dateChanged();
    partial void Onph_update_dateChanging(string value);
    partial void Onph_update_dateChanged();
    partial void Onph_perChanging(string value);
    partial void Onph_perChanged();
    partial void Onph_update_perChanging(string value);
    partial void Onph_update_perChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    #endregion
		
		public PeiHuo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string zhid
		{
			get
			{
				return this._zhid;
			}
			set
			{
				if ((this._zhid != value))
				{
					this.OnzhidChanging(value);
					this.SendPropertyChanging();
					this._zhid = value;
					this.SendPropertyChanged("zhid");
					this.OnzhidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_id", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string use_id
		{
			get
			{
				return this._use_id;
			}
			set
			{
				if ((this._use_id != value))
				{
					this.Onuse_idChanging(value);
					this.SendPropertyChanging();
					this._use_id = value;
					this.SendPropertyChanged("use_id");
					this.Onuse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string style
		{
			get
			{
				return this._style;
			}
			set
			{
				if ((this._style != value))
				{
					this.OnstyleChanging(value);
					this.SendPropertyChanging();
					this._style = value;
					this.SendPropertyChanged("style");
					this.OnstyleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s105", DbType="Int")]
		public System.Nullable<int> s105
		{
			get
			{
				return this._s105;
			}
			set
			{
				if ((this._s105 != value))
				{
					this.Ons105Changing(value);
					this.SendPropertyChanging();
					this._s105 = value;
					this.SendPropertyChanged("s105");
					this.Ons105Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m120", DbType="Int")]
		public System.Nullable<int> m120
		{
			get
			{
				return this._m120;
			}
			set
			{
				if ((this._m120 != value))
				{
					this.Onm120Changing(value);
					this.SendPropertyChanging();
					this._m120 = value;
					this.SendPropertyChanged("m120");
					this.Onm120Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l130", DbType="Int")]
		public System.Nullable<int> l130
		{
			get
			{
				return this._l130;
			}
			set
			{
				if ((this._l130 != value))
				{
					this.Onl130Changing(value);
					this.SendPropertyChanging();
					this._l130 = value;
					this.SendPropertyChanged("l130");
					this.Onl130Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xl140", DbType="Int")]
		public System.Nullable<int> xl140
		{
			get
			{
				return this._xl140;
			}
			set
			{
				if ((this._xl140 != value))
				{
					this.Onxl140Changing(value);
					this.SendPropertyChanging();
					this._xl140 = value;
					this.SendPropertyChanged("xl140");
					this.Onxl140Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xxl155", DbType="Int")]
		public System.Nullable<int> xxl155
		{
			get
			{
				return this._xxl155;
			}
			set
			{
				if ((this._xxl155 != value))
				{
					this.Onxxl155Changing(value);
					this.SendPropertyChanging();
					this._xxl155 = value;
					this.SendPropertyChanged("xxl155");
					this.Onxxl155Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_num", DbType="Int")]
		public System.Nullable<int> total_num
		{
			get
			{
				return this._total_num;
			}
			set
			{
				if ((this._total_num != value))
				{
					this.Ontotal_numChanging(value);
					this.SendPropertyChanging();
					this._total_num = value;
					this.SendPropertyChanged("total_num");
					this.Ontotal_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unt_pr", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> unt_pr
		{
			get
			{
				return this._unt_pr;
			}
			set
			{
				if ((this._unt_pr != value))
				{
					this.Onunt_prChanging(value);
					this.SendPropertyChanging();
					this._unt_pr = value;
					this.SendPropertyChanged("unt_pr");
					this.Onunt_prChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_money", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total_money
		{
			get
			{
				return this._total_money;
			}
			set
			{
				if ((this._total_money != value))
				{
					this.Ontotal_moneyChanging(value);
					this.SendPropertyChanging();
					this._total_money = value;
					this.SendPropertyChanged("total_money");
					this.Ontotal_moneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph_date", DbType="VarChar(30)")]
		public string ph_date
		{
			get
			{
				return this._ph_date;
			}
			set
			{
				if ((this._ph_date != value))
				{
					this.Onph_dateChanging(value);
					this.SendPropertyChanging();
					this._ph_date = value;
					this.SendPropertyChanged("ph_date");
					this.Onph_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph_update_date", DbType="VarChar(30)")]
		public string ph_update_date
		{
			get
			{
				return this._ph_update_date;
			}
			set
			{
				if ((this._ph_update_date != value))
				{
					this.Onph_update_dateChanging(value);
					this.SendPropertyChanging();
					this._ph_update_date = value;
					this.SendPropertyChanged("ph_update_date");
					this.Onph_update_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph_per", DbType="VarChar(30)")]
		public string ph_per
		{
			get
			{
				return this._ph_per;
			}
			set
			{
				if ((this._ph_per != value))
				{
					this.Onph_perChanging(value);
					this.SendPropertyChanging();
					this._ph_per = value;
					this.SendPropertyChanged("ph_per");
					this.Onph_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ph_update_per", DbType="VarChar(30)")]
		public string ph_update_per
		{
			get
			{
				return this._ph_update_per;
			}
			set
			{
				if ((this._ph_update_per != value))
				{
					this.Onph_update_perChanging(value);
					this.SendPropertyChanging();
					this._ph_update_per = value;
					this.SendPropertyChanged("ph_update_per");
					this.Onph_update_perChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(1000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_info")]
	public partial class user_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _user_pass;
		
		private int _role_id;
		
		private string _create_date;
		
		private string _update_date;
		
		private string _last_login_date;
		
		private string _remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    partial void Onrole_idChanging(int value);
    partial void Onrole_idChanged();
    partial void Oncreate_dateChanging(string value);
    partial void Oncreate_dateChanged();
    partial void Onupdate_dateChanging(string value);
    partial void Onupdate_dateChanged();
    partial void Onlast_login_dateChanging(string value);
    partial void Onlast_login_dateChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    #endregion
		
		public user_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="Int NOT NULL")]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="VarChar(30)")]
		public string create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="VarChar(30)")]
		public string update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login_date", DbType="VarChar(30)")]
		public string last_login_date
		{
			get
			{
				return this._last_login_date;
			}
			set
			{
				if ((this._last_login_date != value))
				{
					this.Onlast_login_dateChanging(value);
					this.SendPropertyChanging();
					this._last_login_date = value;
					this.SendPropertyChanged("last_login_date");
					this.Onlast_login_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(1000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.role_info")]
	public partial class role_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _role_id;
		
		private string _role_name;
		
		private string _remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrole_idChanging(int value);
    partial void Onrole_idChanged();
    partial void Onrole_nameChanging(string value);
    partial void Onrole_nameChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    #endregion
		
		public role_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_name", DbType="VarChar(30)")]
		public string role_name
		{
			get
			{
				return this._role_name;
			}
			set
			{
				if ((this._role_name != value))
				{
					this.Onrole_nameChanging(value);
					this.SendPropertyChanging();
					this._role_name = value;
					this.SendPropertyChanged("role_name");
					this.Onrole_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="VarChar(1000)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class getdpResult
	{
		
		private System.Nullable<decimal> _mqu;
		
		private string _masterstyle;
		
		private string _mdate;
		
		private decimal _lqu1;
		
		private string _legging1;
		
		private string _datel1;
		
		private decimal _lqu2;
		
		private string _legging2;
		
		private string _datel2;
		
		private decimal _bqu1;
		
		private string _bottom1;
		
		private string _dateb1;
		
		private decimal _bqu2;
		
		private string _bottom2;
		
		private string _dateb2;
		
		private decimal _aqu1;
		
		private string _accessory1;
		
		private string _datea1;
		
		private decimal _aqu2;
		
		private string _accessory2;
		
		private string _datea2;
		
		private string _cbpicture;
		
		private string _isdp;
		
		public getdpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mqu", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> mqu
		{
			get
			{
				return this._mqu;
			}
			set
			{
				if ((this._mqu != value))
				{
					this._mqu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masterstyle", DbType="VarChar(50)")]
		public string masterstyle
		{
			get
			{
				return this._masterstyle;
			}
			set
			{
				if ((this._masterstyle != value))
				{
					this._masterstyle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mdate", DbType="VarChar(50)")]
		public string mdate
		{
			get
			{
				return this._mdate;
			}
			set
			{
				if ((this._mdate != value))
				{
					this._mdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lqu1", DbType="Decimal(38,0) NOT NULL")]
		public decimal lqu1
		{
			get
			{
				return this._lqu1;
			}
			set
			{
				if ((this._lqu1 != value))
				{
					this._lqu1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_legging1", DbType="VarChar(50)")]
		public string legging1
		{
			get
			{
				return this._legging1;
			}
			set
			{
				if ((this._legging1 != value))
				{
					this._legging1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datel1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string datel1
		{
			get
			{
				return this._datel1;
			}
			set
			{
				if ((this._datel1 != value))
				{
					this._datel1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lqu2", DbType="Decimal(38,0) NOT NULL")]
		public decimal lqu2
		{
			get
			{
				return this._lqu2;
			}
			set
			{
				if ((this._lqu2 != value))
				{
					this._lqu2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_legging2", DbType="VarChar(50)")]
		public string legging2
		{
			get
			{
				return this._legging2;
			}
			set
			{
				if ((this._legging2 != value))
				{
					this._legging2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datel2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string datel2
		{
			get
			{
				return this._datel2;
			}
			set
			{
				if ((this._datel2 != value))
				{
					this._datel2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqu1", DbType="Decimal(38,0) NOT NULL")]
		public decimal bqu1
		{
			get
			{
				return this._bqu1;
			}
			set
			{
				if ((this._bqu1 != value))
				{
					this._bqu1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottom1", DbType="VarChar(50)")]
		public string bottom1
		{
			get
			{
				return this._bottom1;
			}
			set
			{
				if ((this._bottom1 != value))
				{
					this._bottom1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateb1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dateb1
		{
			get
			{
				return this._dateb1;
			}
			set
			{
				if ((this._dateb1 != value))
				{
					this._dateb1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bqu2", DbType="Decimal(38,0) NOT NULL")]
		public decimal bqu2
		{
			get
			{
				return this._bqu2;
			}
			set
			{
				if ((this._bqu2 != value))
				{
					this._bqu2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bottom2", DbType="VarChar(50)")]
		public string bottom2
		{
			get
			{
				return this._bottom2;
			}
			set
			{
				if ((this._bottom2 != value))
				{
					this._bottom2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateb2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dateb2
		{
			get
			{
				return this._dateb2;
			}
			set
			{
				if ((this._dateb2 != value))
				{
					this._dateb2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aqu1", DbType="Decimal(38,0) NOT NULL")]
		public decimal aqu1
		{
			get
			{
				return this._aqu1;
			}
			set
			{
				if ((this._aqu1 != value))
				{
					this._aqu1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory1", DbType="VarChar(50)")]
		public string accessory1
		{
			get
			{
				return this._accessory1;
			}
			set
			{
				if ((this._accessory1 != value))
				{
					this._accessory1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datea1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string datea1
		{
			get
			{
				return this._datea1;
			}
			set
			{
				if ((this._datea1 != value))
				{
					this._datea1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aqu2", DbType="Decimal(38,0) NOT NULL")]
		public decimal aqu2
		{
			get
			{
				return this._aqu2;
			}
			set
			{
				if ((this._aqu2 != value))
				{
					this._aqu2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accessory2", DbType="VarChar(50)")]
		public string accessory2
		{
			get
			{
				return this._accessory2;
			}
			set
			{
				if ((this._accessory2 != value))
				{
					this._accessory2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datea2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string datea2
		{
			get
			{
				return this._datea2;
			}
			set
			{
				if ((this._datea2 != value))
				{
					this._datea2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbpicture", DbType="VarChar(50)")]
		public string cbpicture
		{
			get
			{
				return this._cbpicture;
			}
			set
			{
				if ((this._cbpicture != value))
				{
					this._cbpicture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdp", DbType="VarChar(1000)")]
		public string isdp
		{
			get
			{
				return this._isdp;
			}
			set
			{
				if ((this._isdp != value))
				{
					this._isdp = value;
				}
			}
		}
	}
	
	public partial class zhizhaodan_procResult
	{
		
		private System.Nullable<decimal> _com_qu;
		
		private string _com_id;
		
		private string _col_no;
		
		private string _com_nm;
		
		private string _sty_no;
		
		private string _col_dr;
		
		private string _siz_no;
		
		private string _siz_dr;
		
		private System.Nullable<int> _siz_id;
		
		private System.Nullable<decimal> _unt_pr;
		
		public zhizhaodan_procResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_qu", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> com_qu
		{
			get
			{
				return this._com_qu;
			}
			set
			{
				if ((this._com_qu != value))
				{
					this._com_qu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_id", DbType="VarChar(8000)")]
		public string com_id
		{
			get
			{
				return this._com_id;
			}
			set
			{
				if ((this._com_id != value))
				{
					this._com_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_col_no", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string col_no
		{
			get
			{
				return this._col_no;
			}
			set
			{
				if ((this._col_no != value))
				{
					this._col_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_nm", DbType="VarChar(100)")]
		public string com_nm
		{
			get
			{
				return this._com_nm;
			}
			set
			{
				if ((this._com_nm != value))
				{
					this._com_nm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sty_no", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string sty_no
		{
			get
			{
				return this._sty_no;
			}
			set
			{
				if ((this._sty_no != value))
				{
					this._sty_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_col_dr", DbType="VarChar(100)")]
		public string col_dr
		{
			get
			{
				return this._col_dr;
			}
			set
			{
				if ((this._col_dr != value))
				{
					this._col_dr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siz_no", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string siz_no
		{
			get
			{
				return this._siz_no;
			}
			set
			{
				if ((this._siz_no != value))
				{
					this._siz_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siz_dr", DbType="VarChar(100)")]
		public string siz_dr
		{
			get
			{
				return this._siz_dr;
			}
			set
			{
				if ((this._siz_dr != value))
				{
					this._siz_dr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siz_id", DbType="Int")]
		public System.Nullable<int> siz_id
		{
			get
			{
				return this._siz_id;
			}
			set
			{
				if ((this._siz_id != value))
				{
					this._siz_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unt_pr", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> unt_pr
		{
			get
			{
				return this._unt_pr;
			}
			set
			{
				if ((this._unt_pr != value))
				{
					this._unt_pr = value;
				}
			}
		}
	}
	
	public partial class GetPeiHuo_ProcResult
	{
		
		private string _use_id;
		
		private string _use_nm;
		
		private string _style;
		
		private System.Nullable<int> _s105;
		
		private System.Nullable<int> _m120;
		
		private System.Nullable<int> _l130;
		
		private System.Nullable<int> _xl140;
		
		private System.Nullable<int> _xxl155;
		
		private System.Nullable<int> _total_num;
		
		private System.Nullable<decimal> _unt_pr;
		
		private System.Nullable<decimal> _total_money;
		
		public GetPeiHuo_ProcResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_id", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string use_id
		{
			get
			{
				return this._use_id;
			}
			set
			{
				if ((this._use_id != value))
				{
					this._use_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_nm", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string use_nm
		{
			get
			{
				return this._use_nm;
			}
			set
			{
				if ((this._use_nm != value))
				{
					this._use_nm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style", DbType="VarChar(50)")]
		public string style
		{
			get
			{
				return this._style;
			}
			set
			{
				if ((this._style != value))
				{
					this._style = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s105", DbType="Int")]
		public System.Nullable<int> s105
		{
			get
			{
				return this._s105;
			}
			set
			{
				if ((this._s105 != value))
				{
					this._s105 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m120", DbType="Int")]
		public System.Nullable<int> m120
		{
			get
			{
				return this._m120;
			}
			set
			{
				if ((this._m120 != value))
				{
					this._m120 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l130", DbType="Int")]
		public System.Nullable<int> l130
		{
			get
			{
				return this._l130;
			}
			set
			{
				if ((this._l130 != value))
				{
					this._l130 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xl140", DbType="Int")]
		public System.Nullable<int> xl140
		{
			get
			{
				return this._xl140;
			}
			set
			{
				if ((this._xl140 != value))
				{
					this._xl140 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xxl155", DbType="Int")]
		public System.Nullable<int> xxl155
		{
			get
			{
				return this._xxl155;
			}
			set
			{
				if ((this._xxl155 != value))
				{
					this._xxl155 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_num", DbType="Int")]
		public System.Nullable<int> total_num
		{
			get
			{
				return this._total_num;
			}
			set
			{
				if ((this._total_num != value))
				{
					this._total_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unt_pr", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> unt_pr
		{
			get
			{
				return this._unt_pr;
			}
			set
			{
				if ((this._unt_pr != value))
				{
					this._unt_pr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_money", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total_money
		{
			get
			{
				return this._total_money;
			}
			set
			{
				if ((this._total_money != value))
				{
					this._total_money = value;
				}
			}
		}
	}
	
	public partial class GetMan_No_ProcResult
	{
		
		private string _Man_no;
		
		private string _Sys_dt;
		
		public GetMan_No_ProcResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Man_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Man_no
		{
			get
			{
				return this._Man_no;
			}
			set
			{
				if ((this._Man_no != value))
				{
					this._Man_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sys_dt", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Sys_dt
		{
			get
			{
				return this._Sys_dt;
			}
			set
			{
				if ((this._Sys_dt != value))
				{
					this._Sys_dt = value;
				}
			}
		}
	}
	
	public partial class Out_Excel_ProcResult
	{
		
		private string _use_nm;
		
		private string _style;
		
		private string _com_nm;
		
		private string _col_dr;
		
		private int _s105;
		
		private int _m120;
		
		private int _l130;
		
		private int _xl140;
		
		private int _xxl155;
		
		private int _total_num;
		
		private decimal _unt_pr;
		
		private System.Nullable<decimal> _total_money;
		
		public Out_Excel_ProcResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_nm", DbType="VarChar(100)")]
		public string use_nm
		{
			get
			{
				return this._use_nm;
			}
			set
			{
				if ((this._use_nm != value))
				{
					this._use_nm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string style
		{
			get
			{
				return this._style;
			}
			set
			{
				if ((this._style != value))
				{
					this._style = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_nm", DbType="VarChar(100)")]
		public string com_nm
		{
			get
			{
				return this._com_nm;
			}
			set
			{
				if ((this._com_nm != value))
				{
					this._com_nm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_col_dr", DbType="VarChar(100)")]
		public string col_dr
		{
			get
			{
				return this._col_dr;
			}
			set
			{
				if ((this._col_dr != value))
				{
					this._col_dr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s105", DbType="Int NOT NULL")]
		public int s105
		{
			get
			{
				return this._s105;
			}
			set
			{
				if ((this._s105 != value))
				{
					this._s105 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m120", DbType="Int NOT NULL")]
		public int m120
		{
			get
			{
				return this._m120;
			}
			set
			{
				if ((this._m120 != value))
				{
					this._m120 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_l130", DbType="Int NOT NULL")]
		public int l130
		{
			get
			{
				return this._l130;
			}
			set
			{
				if ((this._l130 != value))
				{
					this._l130 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xl140", DbType="Int NOT NULL")]
		public int xl140
		{
			get
			{
				return this._xl140;
			}
			set
			{
				if ((this._xl140 != value))
				{
					this._xl140 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xxl155", DbType="Int NOT NULL")]
		public int xxl155
		{
			get
			{
				return this._xxl155;
			}
			set
			{
				if ((this._xxl155 != value))
				{
					this._xxl155 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_num", DbType="Int NOT NULL")]
		public int total_num
		{
			get
			{
				return this._total_num;
			}
			set
			{
				if ((this._total_num != value))
				{
					this._total_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unt_pr", DbType="Decimal(18,0) NOT NULL")]
		public decimal unt_pr
		{
			get
			{
				return this._unt_pr;
			}
			set
			{
				if ((this._unt_pr != value))
				{
					this._unt_pr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_money", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> total_money
		{
			get
			{
				return this._total_money;
			}
			set
			{
				if ((this._total_money != value))
				{
					this._total_money = value;
				}
			}
		}
	}
	
	public partial class get_user_roleResult
	{
		
		private string _role_name;
		
		public get_user_roleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_name", DbType="VarChar(30)")]
		public string role_name
		{
			get
			{
				return this._role_name;
			}
			set
			{
				if ((this._role_name != value))
				{
					this._role_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
